examples/toolchains/rust: Update rules_rust
Pinning the cargo dependencies failed with:

Error: Failed to write registry URLs and feature map

Caused by:
    0: Failed to get crate index config
    1: No such file or directory (os error 2)

So at least 0.58.0 is required, which depends on platforms >= 0.0.11.

Also, disable bzlmod for the time being.