Fix error running //tests:run-test-invalid-nixpkgs-package
```
ERROR: /private/var/tmp/_bazel_runner/a4a3182e50c9460fa52b8c6c1e6f916f/sandbox/processwrapper-sandbox/9/execroot/io_tweag_rules_nixpkgs/bazel-out/darwin-fastbuild/bin/tests/run-test-invalid-nixpkgs-package.runfiles/io_tweag_rules_nixpkgs/WORKSPACE:20:27: fetching local_repository rule //external:rules_nixpkgs_nodejs: java.io.IOException: The repository's path is "./toolchains/nodejs" (absolute: "/private/var/tmp/_bazel_runner/a4a3182e50c9460fa52b8c6c1e6f916f/sandbox/processwrapper-sandbox/9/execroot/io_tweag_rules_nixpkgs/bazel-out/darwin-fastbuild/bin/tests/run-test-invalid-nixpkgs-package.runfiles/io_tweag_rules_nixpkgs/toolchains/nodejs") but it does not exist or is not a directory.
ERROR: no such package '@rules_nixpkgs_nodejs//': The repository's path is
"./toolchains/nodejs" (absolute:
"/private/var/tmp/_bazel_runner/a4a3182e50c9460fa52b8c6c1e6f916f/sandbox/processwrapper-sandbox/9/execroot/io_tweag_rules_nixpkgs/bazel-out/darwin-fastbuild/bin/tests/run-test-invalid-nixpkgs-package.runfiles/io_tweag_rules_nixpkgs/toolchains/nodejs")
but it does not exist or is not a directory.
```