update rules_java to 7.12.2 and use jdk17 by default
Newer versions of rules_java require newer versions of the JDK,
as indicated by the following message:

  ---8<---8<--- Start of log, file at /home/runner/.cache/bazel/_bazel_runner/9b846b853a4cc307dac457b219fea0d4/bazel-workers/multiplex-worker-1-Javac.log ---8<---8<---
  Error thrown by worker thread, shutting down worker.
  java.lang.UnsupportedClassVersionError: com/google/errorprone/InvalidCommandLineOptionException has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.