Use `nix_2_4` from `@nixpkgs` for test_invalid_nixpkgs_package test
Before, the `nixUnstable` package from nixpkgs commit
15d1011615d16a8b731adf28e2cfc33481102780 was used which would resolve to nix
version 2.4pre7534_b92f58f6.

This old version of nixpkgs from May 2020 lacks support for MacOS Big Sur (11)
which is only available as of nixpkgs release 21.11 and thus running Bazel
failed:

```
$ bazel test //...
error: cannot coerce null to a string

       at /private/var/tmp/_bazel_builder/ff9a81a9a8bde7159a03f31985635bae/external/remote_nixpkgs_for_nix_unstable/pkgs/stdenv/generic/make-derivation.nix:192:34:

          191|         // (lib.optionalAttrs (!(attrs ? name) && attrs ? pname && attrs ? version)) {
          192|           name = "${attrs.pname}-${attrs.version}";
             |                                  ^
          193|         } // (lib.optionalAttrs (stdenv.hostPlatform != stdenv.buildPlatform && !dontAddHostSuffix && (attrs ? name || (attrs ? pname && attrs ? version)))) {
(use '--show-trace' to show detailed location information)
INFO: Repository nix-unstable instantiated at:
  /Users/builder/claudio-rules_nixpkgs/WORKSPACE:41:16: in <toplevel>
  /private/var/tmp/_bazel_builder/ff9a81a9a8bde7159a03f31985635bae/external/rules_nixpkgs_core/nixpkgs.bzl:382:21: in nixpkgs_package
Repository rule _nixpkgs_package defined at:
  /private/var/tmp/_bazel_builder/ff9a81a9a8bde7159a03f31985635bae/external/rules_nixpkgs_core/nixpkgs.bzl:276:35: in <toplevel>
ERROR: An error occurred during the fetch of repository 'nix-unstable':
   Traceback (most recent call last):
        File "/private/var/tmp/_bazel_builder/ff9a81a9a8bde7159a03f31985635bae/external/rules_nixpkgs_core/nixpkgs.bzl", line 242, column 38, in _nixpkgs_package_impl
                exec_result = execute_or_fail(
        File "/private/var/tmp/_bazel_builder/ff9a81a9a8bde7159a03f31985635bae/external/rules_nixpkgs_core/util.bzl", line 59, column 13, in execute_or_fail
                fail("""
Error in fail:
Cannot build Nix attribute 'nixUnstable'.
Command: [/nix/var/nix/profiles/default/bin/nix-build, "-E", "import <nixpkgs> { config = {}; overlays = []; }", "-A", "nixUnstable", "--out-link", "bazel-support/nix-out-link", "-I", "nixpkgs=/private/var/tmp/_bazel_builder/ff9a81a9a8bde7159a03f31985635bae/external/remote_nixpkgs_for_nix_unstable/remote_nixpkgs_for_nix_unstable"]
Return code: 1
```

Switch to nix_2_4 and remove the remote_nixpkgs_for_nix_unstable repository.